name: Build
on:
  workflow_dispatch:
      inputs:
        package_name:
          description: "Package name of the game:"
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
    - name: Extract package suffix
      id: extract_package
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - run: |
        chmod +x ./gradlew
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
        ./gradlew :module:assembleRelease
        package_name="${{ github.event.inputs.package_name }}"
        if [[ "$package_name" == *.* ]]; then
          suffix="${package_name##*.}"
        else
          suffix="$package_name"
        fi
        echo "suffix=$suffix" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@v4
      with:
        name: zygisk-il2cppdumper-${{ steps.extract_package.outputs.suffix }}
        path: out/magisk_module_release/
        pattern: zygisk-il2cppdumper-*
        merge-multiple: true
